spring:
  freemarker:
    expose-spring-macro-helpers: true
    suffix: .html
    template-loader-path:
      - classpath:/public/ 
     
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: true
#  redis:
#    pool:
#      max-active: 20
#      max-wait: 10
#      min-idle: 10
#      max-idle: 20
#    sentinel:
#      master: jtcldvpra04
#      nodes: 10.0.60.88:26379,10.0.60.89:26379
  datasource:
    name: Webedu
    platform: mysql
    driver-class-name:  com.mysql.jdbc.Driver 
    url: jdbc:mysql://127.0.0.1:3306/eduweb?useUnicode\=true&amp;characterEncoding\=UTF-8
    username: scott
    password: orcl
    maximum-pool-size: 200
    connection-timeout: 28000000
    min-idle: 10
    max-idle: 10
    test-on-borrow: true
    validation-query: SELECT 1
    
flyway:
  enabled: true
  baselineOnMigrate: true
    
#security:
#  user:
#    password:
#     admin
#   name: admin
# sessions: ALWAYS
  
  
  
  
  